---
  environment: production
  chdir: /z/distro/waitress
  address: 127.0.0.1
  user: root
  group: root
  port: 8000
  pid: /var/run/waitress.pid
  rackup: /z/distro/waitress/config.ru
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true